### ISSUE TITLE
Add tests for insertion into docs

### ISSUE THREAD

**Issue by matteobachetti** [StingraySoftware/notebooks#52]
We should have a test that compiles the notebook into the Stingray documentation, to check if there are inconsistent titles or other problems that make the sphinx build fail.
Any ideas?

**Comment by AnonymousCodes911** [comment]
@matteobachetti, 
Are we still pursuing this ?

**Comment by matteobachetti** [comment]
Yes! This would be very useful

**Comment by AnonymousCodes911** [comment]
@matteobachetti, 
I think we can use the Jupyter Book it has built-in support for executing notebooks and including them in the documentation(by converting them into HTML). we can create a notebook which will compile all the notebooks and tell us about the errors(?) if any, or we can rely on Jupyter Book's built-in error reporting.

**Comment by AnonymousCodes911** [comment]
duly noted, i will start working on this , in the mean time would you assign me this issue?

**Comment by AnonymousCodes911** [comment]
@matteobachetti,
So after reading the docs, i think i have a basic scaffolding ready for the  Github Action workflow (creating a build_docs.yml),  and i just need help with the correct paths and commands to match the repo's structure and build processes.
Thank you!
