### ISSUE TITLE
Broken link in Spectral Timing Notebook

### ISSUE THREAD

**Issue by dhuppenkothen** [StingraySoftware/notebooks#71]
The docs check on the GPTool pull request is complaining because of what it considers a broken link, with the following error message:

`Warning, treated as error:
/home/runner/work/stingray/stingray/docs/notebooks/Spectral Timing/Spectral Timing Exploration.ipynb:233:broken link: https://ui.adsabs.harvard.edu/abs/1992ApJ...391L..21M/abstract (404 Client Error: NOT FOUND for url: https://ui.adsabs.harvard.edu/abs/1992ApJ...391L..21M/abstract)`

I don't know if that's a real issue or GitHub Actions doing something weird, but noting it here for future investigation.

**Comment by matteobachetti** [comment]
It's weird, I had never seen links disappear from ADSABS before. But the link has indeed disappeared 😱

**Comment by dhuppenkothen** [comment]
👻

**Comment by matteobachetti** [comment]
Apparently, it's back

**Comment by matteobachetti** [comment]
I think this was solved
