### ISSUE TITLE
 Modeling Notebook

### ISSUE THREAD

**Issue by AnonymousCodes911** [StingraySoftware/notebooks#81]
the arrays `ps.freq` and `res.mfit` have different lengths, thus while running they return ValueError.

**Comment by AnonymousCodes911** [comment]
While trying to replicate the issue ,  cell 47 takes unexpectedly long to execute. 
`sample = parest.sample(lpost, res.p_opt, cov=res.cov, nwalkers=400, 
     niter=100, burnin=300, namestr="psd_modeling_test")
`

**Comment by matteobachetti** [comment]
It's expected 😅 . MCMC sampling takes long!

**Comment by AnonymousCodes911** [comment]
it worked !
